/**
 * Central site configuration for Blue Fox AI Tech Solutions.
 * Model: clients deposit funds, rent a forex robot on an 18/24-month
 * contract, and earn a monthly return (fixed floor + variable upside)
 * which they withdraw from their wallet.
 */

export const site = {
  name: "Blue Fox AI Tech Solutions",
  shortName: "Blue Fox",
  tagline: "Let AI Forex Robots Grow Your Capital",
  description:
    "Blue Fox AI Tech Solutions puts your capital to work with professional forex trading robots. Deposit, choose a robot, and earn a monthly return paid straight to your wallet — withdraw anytime in crypto, bank or cash.",
  url: "https://bluefoxdubai.com",
  email: "support@bluefoxdubai.com",
  phone: "+971 50 000 0000",
  whatsapp: "+971500000000",
  location: "Dubai, United Arab Emirates",
  riskWarning:
    "Investing involves risk. Returns are generated by live forex trading and are not bank deposits or guaranteed by any authority. Capital is committed for the contract term. Only invest what you can afford to lose. Past performance does not guarantee future results.",
} as const;

/** One-time registration fee (USD). */
export const REGISTRATION_FEE = 20;

/** Available contract terms in months. */
export const CONTRACT_TERMS = [18, 24] as const;

export type NavItem = { label: string; href: string; tKey?: string };

export const mainNav: NavItem[] = [
  { label: "Home", href: "/", tKey: "nav.home" },
  { label: "About Us", href: "/about", tKey: "nav.about" },
  { label: "Mission", href: "/mission", tKey: "nav.mission" },
  { label: "Vision", href: "/vision", tKey: "nav.vision" },
  { label: "Privacy & Policy", href: "/legal/privacy", tKey: "nav.privacy" },
  { label: "Terms & Condition", href: "/legal/terms", tKey: "nav.terms" },
  { label: "Our Services", href: "/services", tKey: "nav.services" },
  { label: "Contact Us", href: "/contact", tKey: "nav.contact" },
];

export const footerNav: { title: string; titleKey: string; links: NavItem[] }[] = [
  {
    title: "Platform",
    titleKey: "footer.platform",
    links: [
      { label: "Our Services", href: "/services", tKey: "footer.ourServices" },
      { label: "Packages", href: "/#packages", tKey: "footer.packages" },
      { label: "How it works", href: "/#how-it-works", tKey: "footer.howItWorks" },
      { label: "Live Results", href: "/results", tKey: "footer.liveResults" },
    ],
  },
  {
    title: "Account",
    titleKey: "footer.account",
    links: [
      { label: "Register", href: "/register", tKey: "footer.register" },
      { label: "Client Login", href: "/login", tKey: "footer.clientLogin" },
      { label: "Deposit", href: "/portal/deposit", tKey: "footer.deposit" },
      { label: "Withdraw", href: "/portal/withdraw", tKey: "footer.withdraw" },
    ],
  },
  {
    title: "Company",
    titleKey: "footer.company",
    links: [
      { label: "About Us", href: "/about", tKey: "footer.aboutUs" },
      { label: "Our Mission", href: "/mission", tKey: "footer.ourMission" },
      { label: "Our Vision", href: "/vision", tKey: "footer.ourVision" },
      { label: "Contact Us", href: "/contact", tKey: "footer.contactUs" },
    ],
  },
  {
    title: "Legal",
    titleKey: "footer.legal",
    links: [
      { label: "Risk Disclosure", href: "/legal/risk-disclosure", tKey: "footer.riskDisclosure" },
      { label: "Terms of Service", href: "/legal/terms", tKey: "footer.termsOfService" },
      { label: "Privacy Policy", href: "/legal/privacy", tKey: "footer.privacyPolicy" },
      { label: "AML Policy", href: "/legal/aml", tKey: "footer.amlPolicy" },
    ],
  },
];

/** A Blue Fox bot package — fixed deposit + fixed monthly ROI over a term. */
export type BotPackage = {
  slug: string;
  name: string;
  tier: "Golden" | "Diamond";
  /** Fixed deposit amount (USD). */
  deposit: number;
  /** Fixed monthly return on investment (% per month). */
  monthlyRoi: number;
  /** Contract length in months. */
  contractMonths: 18 | 24;
  highlight?: boolean;
};

/** The real Blue Fox bot packages. */
export const packages: BotPackage[] = [
  // 🥇 Golden — 18-month contract
  { slug: "bf-beginner", name: "Bf Beginner Bot", tier: "Golden", deposit: 3333, monthlyRoi: 4, contractMonths: 18 },
  { slug: "bf-trader", name: "Bf Trader Bot", tier: "Golden", deposit: 5555, monthlyRoi: 4.5, contractMonths: 18 },
  { slug: "bf-ex-trader", name: "Bf Ex. Trader Bot", tier: "Golden", deposit: 7777, monthlyRoi: 5, contractMonths: 18, highlight: true },
  { slug: "bf-professional", name: "Bf Professional Bot", tier: "Golden", deposit: 9999, monthlyRoi: 5.5, contractMonths: 18 },
  // 💎 Diamond — 24-month contract
  { slug: "bf-expert", name: "Bf Expert Bot", tier: "Diamond", deposit: 11111, monthlyRoi: 6, contractMonths: 24 },
  { slug: "bf-talent", name: "Bf Talent Bot", tier: "Diamond", deposit: 22222, monthlyRoi: 6.5, contractMonths: 24 },
  { slug: "bf-tycoon", name: "Bf Tycoon Bot", tier: "Diamond", deposit: 33333, monthlyRoi: 7, contractMonths: 24, highlight: true },
  { slug: "bf-infinity", name: "Bf Infinity Bot", tier: "Diamond", deposit: 55555, monthlyRoi: 8, contractMonths: 24 },
];

export const goldenPackages = packages.filter((p) => p.tier === "Golden");
export const diamondPackages = packages.filter((p) => p.tier === "Diamond");

/** Estimated monthly earnings for a package (deposit × monthly ROI). */
export function monthlyEarnings(p: BotPackage) {
  return Math.round((p.deposit * p.monthlyRoi) / 100);
}

/** Shown with the packages — how capital is returned. */
export const capitalReturnNote =
  "Capital is returned in 3 equal parts over the 3 months following your contract term.";

/** The 4-step client journey. */
export const howItWorks = [
  {
    tKey: "howStep1",
    title: "Register",
    text: `Create your account with a one-time $${REGISTRATION_FEE} registration fee and complete a quick verification.`,
  },
  {
    tKey: "howStep2",
    title: "Deposit funds",
    text: "Top up your wallet by crypto (USDT/USDC), bank transfer or arrange a manual deposit. Admin confirms it.",
  },
  {
    tKey: "howStep3",
    title: "Rent a robot",
    text: "Pick a robot and an 18 or 24-month contract. Your capital is allocated and the robot starts trading.",
  },
  {
    tKey: "howStep4",
    title: "Earn & withdraw",
    text: "Receive your monthly return in your wallet and withdraw anytime via crypto, bank or cash.",
  },
];
