/**
 * Central site configuration for Blue Fox Dubai.
 * Model: clients deposit funds, rent a forex robot on an 18/24-month
 * contract, and earn a monthly return (fixed floor + variable upside)
 * which they withdraw from their wallet.
 */

export const site = {
  name: "Blue Fox Dubai",
  shortName: "Blue Fox",
  tagline: "Let AI Forex Robots Grow Your Capital",
  description:
    "Blue Fox Dubai puts your capital to work with professional forex trading robots. Deposit, choose a robot, and earn a monthly return paid straight to your wallet — withdraw anytime in crypto, bank or cash.",
  url: "https://bluefoxdubai.com",
  email: "support@bluefoxdubai.com",
  phone: "+971 50 000 0000",
  whatsapp: "+971500000000",
  location: "Dubai, United Arab Emirates",
  riskWarning:
    "Investing involves risk. Returns are generated by live forex trading and are not bank deposits or guaranteed by any authority. Capital is committed for the contract term. Only invest what you can afford to lose. Past performance does not guarantee future results.",
} as const;

/** One-time registration fee (USD). */
export const REGISTRATION_FEE = 20;

/** Available contract terms in months. */
export const CONTRACT_TERMS = [18, 24] as const;

export type NavItem = { label: string; href: string };

export const mainNav: NavItem[] = [
  { label: "Robots", href: "/robots" },
  { label: "How it works", href: "/#how-it-works" },
  { label: "Results", href: "/results" },
  { label: "About", href: "/about" },
  { label: "Contact", href: "/contact" },
];

export const footerNav: { title: string; links: NavItem[] }[] = [
  {
    title: "Platform",
    links: [
      { label: "Our Robots", href: "/robots" },
      { label: "How it works", href: "/#how-it-works" },
      { label: "Live Results", href: "/results" },
      { label: "Referral Program", href: "/referrals" },
    ],
  },
  {
    title: "Account",
    links: [
      { label: "Register", href: "/register" },
      { label: "Client Login", href: "/login" },
      { label: "Deposit", href: "/portal/deposit" },
      { label: "Withdraw", href: "/portal/withdraw" },
    ],
  },
  {
    title: "Company",
    links: [
      { label: "About Us", href: "/about" },
      { label: "Contact", href: "/contact" },
      { label: "FAQ", href: "/faq" },
      { label: "Support", href: "/support" },
    ],
  },
  {
    title: "Legal",
    links: [
      { label: "Risk Disclosure", href: "/legal/risk-disclosure" },
      { label: "Terms of Service", href: "/legal/terms" },
      { label: "Privacy Policy", href: "/legal/privacy" },
      { label: "AML Policy", href: "/legal/aml" },
    ],
  },
];

/** Sample robot catalogue — replaced by DB `Robot` records later. */
export type Robot = {
  slug: string;
  name: string;
  tagline: string;
  trades: string;
  riskLevel: "Low" | "Medium" | "High";
  /** Guaranteed monthly floor return (%). */
  monthlyReturnFloor: number;
  /** Additional variable upside on top of the floor (%). */
  monthlyReturnUpside: number;
  /** Contract terms offered (months). */
  termMonths: number[];
  minDeposit: number;
  capacity: string;
  badge?: string;
  highlights: string[];
};

export const robots: Robot[] = [
  {
    slug: "night-prowler",
    name: "Night Prowler",
    tagline: "Low-risk capital protection",
    trades: "EURUSD · GBPUSD",
    riskLevel: "Low",
    monthlyReturnFloor: 4,
    monthlyReturnUpside: 2,
    termMonths: [18, 24],
    minDeposit: 500,
    capacity: "Open",
    badge: "Safest",
    highlights: [
      "Conservative scalping strategy",
      "Strict drawdown limits",
      "Ideal for first-time investors",
    ],
  },
  {
    slug: "golden-fox",
    name: "Golden Fox",
    tagline: "Balanced growth on gold",
    trades: "XAUUSD (Gold)",
    riskLevel: "Medium",
    monthlyReturnFloor: 6,
    monthlyReturnUpside: 3,
    termMonths: [18, 24],
    minDeposit: 1000,
    capacity: "Open",
    badge: "Most popular",
    highlights: [
      "Trend + breakout system on gold",
      "Best balance of risk & reward",
      "Most chosen by our clients",
    ],
  },
  {
    slug: "apex-hunter",
    name: "Apex Hunter",
    tagline: "Aggressive growth engine",
    trades: "Majors + Indices",
    riskLevel: "High",
    monthlyReturnFloor: 8,
    monthlyReturnUpside: 4,
    termMonths: [18, 24],
    minDeposit: 5000,
    capacity: "Limited",
    badge: "Highest return",
    highlights: [
      "Momentum multi-pair strategy",
      "Higher target returns",
      "For experienced investors",
    ],
  },
];

/** The 4-step client journey. */
export const howItWorks = [
  {
    title: "Register",
    text: `Create your account with a one-time $${REGISTRATION_FEE} registration fee and complete a quick verification.`,
  },
  {
    title: "Deposit funds",
    text: "Top up your wallet by crypto (USDT/USDC), bank transfer or arrange a manual deposit. Admin confirms it.",
  },
  {
    title: "Rent a robot",
    text: "Pick a robot and an 18 or 24-month contract. Your capital is allocated and the robot starts trading.",
  },
  {
    title: "Earn & withdraw",
    text: "Receive your monthly return in your wallet and withdraw anytime via crypto, bank or cash.",
  },
];
